### ISSUE TITLE
name no found

### ISSUE THREAD

**Issue by royaljx** [Griperis/BlenderImprovedNodeSearch#4]
when i type node group or a renamed node the search isn't able to find it, that's something the base blander do. it does only search existing base nodes name, like: noise, bsdf, etc...
![photo_2024-07-21_17-33-07](https://github.com/user-attachments/assets/1dab94c3-e43e-4a47-9d83-d314b5f9e030)

**Comment by Griperis** [comment]
I will look into it, this should definitelly be supported :)

**Comment by Griperis** [comment]
Should be fixed now.

**Comment by royaljx** [comment]
nice, it work
