### ISSUE TITLE
"Improved Node Search" stops node search from working in the "serpens visual scripting editor" 

### ISSUE THREAD

**Issue by sktvete** [Griperis/BlenderImprovedNodeSearch#5]
"Improved Node Search" stops node search from working in the "serpens visual scripting editor" 

![image](https://github.com/user-attachments/assets/72cbd310-087d-460f-be20-e69ad3fade13)
![image](https://github.com/user-attachments/assets/864f812c-0fb4-48d0-a92b-2f879b80c45f)

**Comment by sktvete** [comment]
Images are Without vs With add-on enabled

**Comment by Griperis** [comment]
Looked into this and it's indeed true, need to adjust:
- interface
- serpens usage of node_tree (not similar to bpy only in node groups)

**Comment by Griperis** [comment]
@sktvete I've released 1.0.4, now the addon is compatible with Serpens, feel free to test it.

**Comment by sktvete** [comment]
Thank you! I'll check it out:)
